name: water-reach-tools

channels:
  - esri
  - conda-forge

dependencies:
  - esri::arcgis
  - dask
  - nodejs
  - numpy
  - pandas
  - pip
  - pyarrow
  - python=3.7
  - python-dotenv
  - shapely
  - swifter
  - pip:
    - azure-storage-blob
    - boto3
    - html2text
