name: water-reach-tools

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - cookiecutter
  - dask
  - fiona
  - h3-py
  - jupyterlab
  - nodejs
  - numpy
  - pandas
  - pip
  - pyarrow
  - pytest
  - python=3.7
  - python-dotenv
  - scipy
  - shapely
  - swifter
  - pip:
    - bump2version
    - html2text
    - ipykernel
    - placekey
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx_rtd_theme
    - twine
